export const siteConfig = {
  name: 'RflowZ',
  legalName: 'RFlowZ-SS',
  tagline: 'AI Research Proposal Writer with OpenAlex & Grounded RAG',
  description:
    'Write research proposals faster with Ask Prof Z, OpenAlex source Library, RAG-grounded literature synthesis, citation integrity checks, and DOCX, PDF, and PPTX export. Start free with no credit card required.',
  url: 'https://rflowz.com',
  appUrl: 'https://app.rflowz.com',
  ogImage: 'https://app.rflowz.com/images/rflowz-og-image.png',
  locale: 'en_MY',
  email: 'support@rflowz.com',
  googleAnalyticsId: 'G-HPFJDV88NG',
  keywords: [
    'AI research proposal writer',
    'research proposal generator',
    'Ask Prof Z',
    'academic AI writing assistant',
    'OpenAlex literature review',
    'grounded literature synthesis',
    'RAG academic writing',
    'research source library',
    'thesis proposal',
    'dissertation proposal',
    'PhD research proposal',
    'research proposal export DOCX PDF',
    'research proposal',
    'academic writing',
  ],
} as const
